# Build all services:
# docker compose build

# Run all services:
# docker compose up

# Stop and remove all services:
# docker compose down

services:

  open_loop:
    build:
      context: .

    volumes:
      - ./plots:/app/plots

    command: python src/ml_pid_tuning/simulations/open_loop.py


  close_loop:
    build:
      context: .

    volumes:
      - ./plots:/app/plots

    command: python src/ml_pid_tuning/simulations/close_loop.py