# Build all services:
# docker compose build

# Run all services:
# docker compose up

# Stop and remove all services:
# docker compose down

services:

  tests:
    build:
      context: .

    command: pytest -v

  open_loop:
    build:
      context: .

    volumes:
      - ./plots:/app/plots

    command: python src/ml_pid_tuning/simulations/open_loop.py

    depends_on:
      tests:
        condition: service_completed_successfully

  close_loop:
    build:
      context: .

    volumes:
      - ./plots:/app/plots

    command: python src/ml_pid_tuning/simulations/close_loop.py

    depends_on:
      open_loop:
        condition: service_completed_successfully
